name: S3 Sync Data Folders

on:
  push:
    branches:
    - dev
    - main
    paths:
    - terraform/**
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github actions repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Copy files to batch-data-bucket-virginia
        run: aws s3 sync s3://noelnamai/hg38 s3://batch-data-bucket-virginia/hg38
  