name: Terraform Security Scanner

on:
  push:
    branches:
    - dev
    - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone Github actions repository
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload sarif file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
